--
-- PostgreSQL database dump
--

\restrict e1TL9lquG8wiBQ7xaQVhIOAubhLe5To53zZorsbFgGM2KXkvp0aywAAby7jMg6y

-- Dumped from database version 16.9 (415ebe8)
-- Dumped by pg_dump version 16.10

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: trips; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

INSERT INTO public.trips (id, title, slug, trip_type, short_title, description, main_image, price, currency, duration_text, location, is_flexible_date, is_fixed_date, is_popular, is_trip_of_week, is_deal, is_goodbye_sharm, created_at, updated_at, is_active, adult_price, child_price) VALUES (10, 'Package D - Pirates Boat & Jeep Safari', 'package-d', 'package', 'Package D', 'Pirates Boat Cruise & Desert Jeep Safari', '/img/trips/package-d.jpg', 110.00, 'USD', '2 Days', 'Sharm El Sheikh', false, false, true, false, false, false, '2025-11-21 04:16:22.144865', '2025-11-21 04:16:22.144865', true, 110.00, 75.00);
INSERT INTO public.trips (id, title, slug, trip_type, short_title, description, main_image, price, currency, duration_text, location, is_flexible_date, is_fixed_date, is_popular, is_trip_of_week, is_deal, is_goodbye_sharm, created_at, updated_at, is_active, adult_price, child_price) VALUES (11, 'Package E - Land & Sea Experience', 'package-e', 'package', 'Package E', 'Ras Mohamed National Park & Desert Rose Safari', '/img/trips/package-e.jpg', 65.00, 'USD', '2 Days', 'Sharm El Sheikh', false, false, true, false, false, false, '2025-11-21 04:16:22.144865', '2025-11-21 04:16:22.144865', true, 65.00, 45.00);
INSERT INTO public.trips (id, title, slug, trip_type, short_title, description, main_image, price, currency, duration_text, location, is_flexible_date, is_fixed_date, is_popular, is_trip_of_week, is_deal, is_goodbye_sharm, created_at, updated_at, is_active, adult_price, child_price) VALUES (12, 'Package K - Ultimate Egyptian Immersion', 'package-k', 'package', 'Package K', 'Sea Scope Red Sea tour & Cairo by Flight + free 20GB SIM', '/img/trips/package-k.jpg', 285.00, 'USD', '2 Days', 'Egypt', false, false, true, false, false, false, '2025-11-21 04:16:22.144865', '2025-11-21 04:16:22.144865', true, 285.00, 270.00);
INSERT INTO public.trips (id, title, slug, trip_type, short_title, description, main_image, price, currency, duration_text, location, is_flexible_date, is_fixed_date, is_popular, is_trip_of_week, is_deal, is_goodbye_sharm, created_at, updated_at, is_active, adult_price, child_price) VALUES (13, 'Dahab Discovery Trip', 'dahab-discovery-trip', 'diving', 'Dahab Discovery', 'Blue Hole, Three Pools snorkeling, Bedouin village, camel riding', '/img/trips/dahab-discovery.jpg', 60.00, 'USD', 'Full Day', 'Dahab', true, false, true, false, false, false, '2025-11-21 04:16:22.144865', '2025-11-21 04:16:22.144865', true, 60.00, 40.00);
INSERT INTO public.trips (id, title, slug, trip_type, short_title, description, main_image, price, currency, duration_text, location, is_flexible_date, is_fixed_date, is_popular, is_trip_of_week, is_deal, is_goodbye_sharm, created_at, updated_at, is_active, adult_price, child_price) VALUES (1, 'Package A – Cairo by Air', 'package-a', 'package', 'Package A', 'Day trip to Cairo by flight with museum and pyramids.', '/img/trips/package-a.jpg', 250.00, 'USD', 'Full Day', 'Cairo', false, true, true, false, false, false, '2025-11-19 05:14:39.094479', '2025-11-19 08:21:54.639244', true, 320.00, 280.00);
INSERT INTO public.trips (id, title, slug, trip_type, short_title, description, main_image, price, currency, duration_text, location, is_flexible_date, is_fixed_date, is_popular, is_trip_of_week, is_deal, is_goodbye_sharm, created_at, updated_at, is_active, adult_price, child_price) VALUES (2, 'Goodbye Sharm – Last Day Program', 'goodbye-sharm', 'package', 'Goodbye Sharm', 'Your final-day special program in Sharm.', '/img/trips/goodbye-sharm.jpg', 15.00, 'USD', 'Full Day', 'Sharm El Sheikh', true, false, true, false, false, true, '2025-11-19 05:14:43.478671', '2025-11-19 08:24:06.445823', true, 15.00, 0.00);
INSERT INTO public.trips (id, title, slug, trip_type, short_title, description, main_image, price, currency, duration_text, location, is_flexible_date, is_fixed_date, is_popular, is_trip_of_week, is_deal, is_goodbye_sharm, created_at, updated_at, is_active, adult_price, child_price) VALUES (3, 'Private Airport Transfer – Sharm', 'private-transfer', 'transfer', 'Private Transfer', 'Airport transfer by private car/minivan.', '/img/trips/private-transfer.jpg', 35.00, 'USD', 'One Way', 'Sharm El Sheikh', true, false, true, false, false, false, '2025-11-19 05:14:47.782646', '2025-11-19 05:14:47.782646', true, 40.00, 40.00);
INSERT INTO public.trips (id, title, slug, trip_type, short_title, description, main_image, price, currency, duration_text, location, is_flexible_date, is_fixed_date, is_popular, is_trip_of_week, is_deal, is_goodbye_sharm, created_at, updated_at, is_active, adult_price, child_price) VALUES (4, 'Cairo by Flight', 'cairo-by-flight', 'tour', 'Cairo Adventure', 'Explore the wonders of Cairo including the Pyramids of Giza, Egyptian Museum, and Khan El Khalili bazaar.', '/img/trips/cairo-flight.jpg', 195.00, 'USD', 'Full Day', 'Cairo', false, true, true, true, false, false, '2025-11-19 05:14:52.307236', '2025-11-19 05:14:52.307236', true, 260.00, 250.00);
INSERT INTO public.trips (id, title, slug, trip_type, short_title, description, main_image, price, currency, duration_text, location, is_flexible_date, is_fixed_date, is_popular, is_trip_of_week, is_deal, is_goodbye_sharm, created_at, updated_at, is_active, adult_price, child_price) VALUES (5, 'Luxor by Flight', 'luxor-by-flight', 'tour', 'Luxor Tour', 'Visit the ancient temples of Luxor, Valley of the Kings, and Karnak Temple by flight from Sharm.', '/img/trips/luxor-flight.jpg', 220.00, 'USD', 'Full Day', 'Luxor', false, true, true, false, false, false, '2025-11-19 05:14:56.664007', '2025-11-19 05:14:56.664007', true, 270.00, 260.00);
INSERT INTO public.trips (id, title, slug, trip_type, short_title, description, main_image, price, currency, duration_text, location, is_flexible_date, is_fixed_date, is_popular, is_trip_of_week, is_deal, is_goodbye_sharm, created_at, updated_at, is_active, adult_price, child_price) VALUES (6, 'Pirates Boat – Ras Mohamed', 'pirates-boat-ras-mohamed', 'boat', 'Pirates Boat', 'Full day snorkeling adventure on the Pirates Boat to Ras Mohamed National Park.', '/img/trips/pirates-boat.jpg', 45.00, 'USD', 'Full Day', 'Ras Mohamed', true, false, true, false, false, false, '2025-11-19 05:15:00.808118', '2025-11-19 05:15:00.808118', true, 60.00, 35.00);
INSERT INTO public.trips (id, title, slug, trip_type, short_title, description, main_image, price, currency, duration_text, location, is_flexible_date, is_fixed_date, is_popular, is_trip_of_week, is_deal, is_goodbye_sharm, created_at, updated_at, is_active, adult_price, child_price) VALUES (7, 'Petra by Boat', 'petra-by-boat', 'tour', 'Petra Tour', 'Journey to Petra, Jordan by boat and discover the ancient Nabatean city.', '/img/trips/petra-boat.jpg', 180.00, 'USD', 'Full Day', 'Petra, Jordan', false, true, true, false, false, false, '2025-11-19 05:15:05.195346', '2025-11-19 05:15:05.195346', true, 250.00, 240.00);
INSERT INTO public.trips (id, title, slug, trip_type, short_title, description, main_image, price, currency, duration_text, location, is_flexible_date, is_fixed_date, is_popular, is_trip_of_week, is_deal, is_goodbye_sharm, created_at, updated_at, is_active, adult_price, child_price) VALUES (8, 'Ras Mohamed Snorkeling', 'ras-mohamed-snorkeling', 'diving', 'Ras Mohamed', 'Snorkeling trip to the stunning coral reefs of Ras Mohamed National Park.', '/img/trips/ras-mohamed.jpg', 40.00, 'USD', 'Half Day', 'Ras Mohamed', true, false, true, false, false, false, '2025-11-19 05:15:09.461729', '2025-11-19 08:23:38.572516', true, 35.00, 20.00);
INSERT INTO public.trips (id, title, slug, trip_type, short_title, description, main_image, price, currency, duration_text, location, is_flexible_date, is_fixed_date, is_popular, is_trip_of_week, is_deal, is_goodbye_sharm, created_at, updated_at, is_active, adult_price, child_price) VALUES (9, 'Package C - Egyptian Explorer Triple Pack', 'package-c', 'package', 'Package C', 'Dahab Discovery, Luxor by Flight & Desert Rose Safari', '/img/trips/package-c.jpg', 360.00, 'USD', '3 Days', 'Egypt', false, false, true, false, false, false, '2025-11-21 04:16:22.144865', '2025-11-21 04:16:22.144865', true, 360.00, 340.00);
INSERT INTO public.trips (id, title, slug, trip_type, short_title, description, main_image, price, currency, duration_text, location, is_flexible_date, is_fixed_date, is_popular, is_trip_of_week, is_deal, is_goodbye_sharm, created_at, updated_at, is_active, adult_price, child_price) VALUES (14, 'Nabeq National Park Jeep Safari', 'nabeq-jeep-safari', 'adventure', 'Nabeq Safari', '4x4 Canyon tour, camel riding, quad biking & Bedouin lunch', '/img/trips/nabeq-safari.jpg', 60.00, 'USD', '7 Hours', 'Nabeq', true, false, true, false, false, false, '2025-11-21 04:16:22.144865', '2025-11-21 04:16:22.144865', true, 60.00, 40.00);
INSERT INTO public.trips (id, title, slug, trip_type, short_title, description, main_image, price, currency, duration_text, location, is_flexible_date, is_fixed_date, is_popular, is_trip_of_week, is_deal, is_goodbye_sharm, created_at, updated_at, is_active, adult_price, child_price) VALUES (15, 'Package B - Custom Egypt Experience', 'package-b', 'package', 'Package B', 'Customizable multi-day Egypt experience', '/img/trips/package-b.jpg', NULL, 'USD', '3 Days', 'Egypt', false, false, true, false, false, false, '2025-11-21 04:53:39.960778', '2025-11-21 04:53:39.960778', true, 295.00, 280.00);
INSERT INTO public.trips (id, title, slug, trip_type, short_title, description, main_image, price, currency, duration_text, location, is_flexible_date, is_fixed_date, is_popular, is_trip_of_week, is_deal, is_goodbye_sharm, created_at, updated_at, is_active, adult_price, child_price) VALUES (16, 'Trip of the Week – Cairo Discovery', 'trip-of-the-week', 'tour', 'Weekly Cairo', 'Weekly featured Cairo tour with special rates', '/img/trips/trip-of-the-week.jpg', NULL, 'USD', 'Full Day', 'Cairo', false, true, true, true, false, false, '2025-11-21 04:53:39.960778', '2025-11-21 04:53:39.960778', true, 180.00, 160.00);
INSERT INTO public.trips (id, title, slug, trip_type, short_title, description, main_image, price, currency, duration_text, location, is_flexible_date, is_fixed_date, is_popular, is_trip_of_week, is_deal, is_goodbye_sharm, created_at, updated_at, is_active, adult_price, child_price) VALUES (17, 'Package 1 — Two-Day Certified Diver Program', 'package-1-diving', 'diving', 'Two-Day Program', 'PADI certified diving program over 2 days', '/img/trips/diving-2day.jpg', NULL, 'USD', '2 Days', 'Red Sea', false, false, false, false, false, false, '2025-11-21 05:16:20.90712', '2025-11-21 05:16:20.90712', true, 150.00, 113.00);
INSERT INTO public.trips (id, title, slug, trip_type, short_title, description, main_image, price, currency, duration_text, location, is_flexible_date, is_fixed_date, is_popular, is_trip_of_week, is_deal, is_goodbye_sharm, created_at, updated_at, is_active, adult_price, child_price) VALUES (18, 'Package 2 — Three Separate Diving Days', 'package-2-diving', 'diving', 'Three Diving Days', 'Three separate days of certified diving adventures', '/img/trips/diving-3days.jpg', NULL, 'USD', '3 Days', 'Red Sea', false, false, false, false, false, false, '2025-11-21 05:16:20.90712', '2025-11-21 05:16:20.90712', true, 220.00, 165.00);
INSERT INTO public.trips (id, title, slug, trip_type, short_title, description, main_image, price, currency, duration_text, location, is_flexible_date, is_fixed_date, is_popular, is_trip_of_week, is_deal, is_goodbye_sharm, created_at, updated_at, is_active, adult_price, child_price) VALUES (19, 'Package 3 — Local Diving + Thistlegorm Wreck', 'package-3-diving', 'diving', 'Wreck Diving', 'Local diving plus the famous Thistlegorm wreck', '/img/trips/diving-wreck.jpg', NULL, 'USD', '2 Days', 'Red Sea', false, false, false, false, false, false, '2025-11-21 05:16:20.90712', '2025-11-21 05:16:20.90712', true, 260.00, 195.00);
INSERT INTO public.trips (id, title, slug, trip_type, short_title, description, main_image, price, currency, duration_text, location, is_flexible_date, is_fixed_date, is_popular, is_trip_of_week, is_deal, is_goodbye_sharm, created_at, updated_at, is_active, adult_price, child_price) VALUES (21, 'Package 4 — PADI Open Water Diver Course', 'package-4-diving', 'diving', 'PADI Open Water', 'PADI Open Water Diver Course - Start your diving certification', '/img/trips/diving-padi-ow.jpg', NULL, 'USD', '3 Days', 'Red Sea', false, false, false, false, false, false, '2025-11-21 05:16:45.304173', '2025-11-21 05:16:45.304173', true, 470.00, 470.00);
INSERT INTO public.trips (id, title, slug, trip_type, short_title, description, main_image, price, currency, duration_text, location, is_flexible_date, is_fixed_date, is_popular, is_trip_of_week, is_deal, is_goodbye_sharm, created_at, updated_at, is_active, adult_price, child_price) VALUES (22, 'Package 5 — PADI Advanced Open Water Course', 'package-5-diving', 'diving', 'PADI Advanced', 'PADI Advanced Open Water Diver Course', '/img/trips/diving-padi-aow.jpg', NULL, 'USD', '2 Days', 'Red Sea', false, false, false, false, false, false, '2025-11-21 05:16:45.304173', '2025-11-21 05:16:45.304173', true, 400.00, 400.00);
INSERT INTO public.trips (id, title, slug, trip_type, short_title, description, main_image, price, currency, duration_text, location, is_flexible_date, is_fixed_date, is_popular, is_trip_of_week, is_deal, is_goodbye_sharm, created_at, updated_at, is_active, adult_price, child_price) VALUES (20, 'Package 6 — Five Separate Diving Days', 'package-6-diving', 'diving', 'Five Diving Days', 'Extended 5-day diving vacation', '/img/trips/diving-5days.jpg', NULL, 'USD', '5 Days', 'Red Sea', false, false, false, false, false, false, '2025-11-21 05:16:20.90712', '2025-11-21 05:16:20.90712', true, 350.00, 263.00);


--
-- Data for Name: trip_dates; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--



--
-- Name: trip_dates_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.trip_dates_id_seq', 1, false);


--
-- Name: trips_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.trips_id_seq', 22, true);


--
-- PostgreSQL database dump complete
--

\unrestrict e1TL9lquG8wiBQ7xaQVhIOAubhLe5To53zZorsbFgGM2KXkvp0aywAAby7jMg6y

